totalPrimeira, totalSegunda, totalTerceira = input().split()
venenoPrimeira, venenoSegunda, venenoTerceira = input().split()
totalPrimeira=int(totalPrimeira)
totalSegunda=int(totalSegunda)
totalTerceira=int(totalTerceira)
venenoPrimeira=int(venenoPrimeira)
venenoSegunda=int(venenoSegunda)
venenoTerceira=int(venenoTerceira)
result = (totalPrimeira+totalSegunda+totalTerceira)-((venenoPrimeira+venenoSegunda+venenoTerceira)*2+(venenoPrimeira+venenoSegunda+venenoTerceira))
print(result)